# Generated by Django 4.1.7 on 2023-09-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slug', models.SlugField()),
                ('img1', models.ImageField(default=None, upload_to='files/cover/')),
                ('img2', models.ImageField(default=None, upload_to='files/cover/')),
                ('img3', models.ImageField(default=None, upload_to='files/cover/')),
                ('stock38', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock39', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock40', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock41', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock42', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock43', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Кроссовки',
                'verbose_name_plural': 'Кроссовки',
            },
        ),
    ]
